# Generated by Django 5.1.7 on 2025-07-17 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='objetivos.estrategia')),
            ],
        ),
        migrations.AddField(
            model_name='estrategia',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='objetivos.objetivo'),
        ),
        migrations.CreateModel(
            name='ObjetivoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='objetivo',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='objetivos.objetivoset'),
        ),
        migrations.CreateModel(
            name='FeedbackAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Identificador de la sección, ej: EG01-propuesta-1_1_EG01', max_length=120)),
                ('acuerdo', models.CharField(choices=[('yes', 'Sí'), ('no', 'No')], max_length=10)),
                ('comoDecir', models.TextField()),
                ('justificacion', models.TextField()),
                ('envio_final', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_avances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback de Avance',
                'verbose_name_plural': 'Feedbacks de Avance',
                'unique_together': {('user', 'clave')},
            },
        ),
    ]
