# Generated by Django 5.1.7 on 2025-07-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackavance',
            name='envio_final',
            field=models.BooleanField(default=False),
        ),
    ]
