# Generated by Django 5.1.7 on 2025-07-17 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estrategia',
            name='clave',
            field=models.CharField(default='temp', max_length=32),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linea',
            name='clave',
            field=models.CharField(default='temp', max_length=32),
        ),
        migrations.AddField(
            model_name='linea',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objetivo',
            name='clave',
            field=models.CharField(default='temp', max_length=32),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='linea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='estrategia',
            unique_together={('user', 'clave')},
        ),
        migrations.AlterUniqueTogether(
            name='linea',
            unique_together={('user', 'clave')},
        ),
        migrations.AlterUniqueTogether(
            name='objetivo',
            unique_together={('user', 'clave')},
        ),
    ]
