# Generated by Django 5.2.3 on 2025-07-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivos', '0002_estrategia_clave_estrategia_user_linea_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrategia',
            name='nombre',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='nombre',
            field=models.CharField(max_length=512),
        ),
    ]
