# Generated by Django 5.2.3 on 2025-07-03 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asIs', models.CharField(max_length=255)),
                ('justification', models.TextField()),
                ('page', models.CharField(max_length=10)),
                ('sectionName', models.CharField(max_length=255)),
                ('shouldBe', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
