# Generated by Django 5.1.7 on 2025-07-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otro_apartados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='envio_final',
            field=models.BooleanField(default=False),
        ),
    ]
