# Generated by Django 5.1.7 on 2025-07-08 00:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Formato: indicador_1_1_A, indicador_2_3_B, etc.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato indicador_1_1_A, indicador_2_3_B, etc.', regex='^indicador_\\d+(_\\d+)*_[A-Z]$')], verbose_name='Clave del Indicador')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del Indicador')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='UserIndicatorSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('selected_indicators', models.ManyToManyField(to='indicadores_eleccion.indicator', verbose_name='Indicadores Seleccionados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Selección de Indicadores del Usuario',
                'verbose_name_plural': 'Selecciones de Indicadores de Usuarios',
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_user_indicator_selection')],
            },
        ),
    ]
