# Generated by Django 5.1.7 on 2025-07-08 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores_eleccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Eje Estratégico', 'verbose_name_plural': 'Ejes Estratégicos'},
        ),
        migrations.AlterModelOptions(
            name='userindicatorselection',
            options={'verbose_name': 'Selección de Ejes del Usuario', 'verbose_name_plural': 'Selecciones de Ejes de Usuarios'},
        ),
        migrations.AlterField(
            model_name='indicator',
            name='code',
            field=models.CharField(help_text='Formato: EG01, ET02, etc.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato EG01, EG02, ET01, ET02, etc.', regex='^(EG|ET)\\d{2}$')], verbose_name='Clave del Eje'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre del Eje'),
        ),
        migrations.AlterField(
            model_name='userindicatorselection',
            name='selected_indicators',
            field=models.ManyToManyField(to='indicadores_eleccion.indicator', verbose_name='Ejes Seleccionados'),
        ),
    ]
