# Generated by Django 5.2.3 on 2025-06-16 19:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategicaxis',
            options={'verbose_name': 'Eje Estratégico', 'verbose_name_plural': 'Ejes Estratégicos'},
        ),
        migrations.AlterModelOptions(
            name='useraxisselection',
            options={'verbose_name': 'Selección de Ejes del Usuario', 'verbose_name_plural': 'Selecciones de Ejes de Usuarios'},
        ),
        migrations.RemoveField(
            model_name='useraxisselection',
            name='axes',
        ),
        migrations.AddField(
            model_name='useraxisselection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraxisselection',
            name='selected_axes',
            field=models.ManyToManyField(to='plataforma.strategicaxis', verbose_name='Ejes Seleccionados'),
        ),
        migrations.AlterField(
            model_name='strategicaxis',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Clave del Eje'),
        ),
        migrations.AlterField(
            model_name='strategicaxis',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre del Eje'),
        ),
        migrations.AlterField(
            model_name='useraxisselection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='useraxisselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
