# Generated by Django 5.2.3 on 2025-06-18 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_strategicaxis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicaxis',
            name='code',
            field=models.CharField(help_text='Formato: EG01, ET02, etc.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato EG01, EG02, ET01, ET02, etc.', regex='^(EG|ET)\\d{2}$')], verbose_name='Clave del Eje'),
        ),
    ]
