# Generated by Django 5.2.3 on 2025-07-03 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_strategicaxis_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='useraxisselection',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_axis_selection'),
        ),
    ]
