# Generated by Django 5.1.7 on 2025-07-29 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('field_name', models.CharField(help_text='Nombre interno del campo en el modelo', max_length=100, verbose_name='Campo revisado')),
                ('is_valid', models.BooleanField(help_text='Marcar Sí (aprobado) o No (rechazado)', verbose_name='¿Aprobado?')),
                ('justification', models.TextField(blank=True, verbose_name='Justificación')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de revisión')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_estrategias', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
            ],
            options={
                'verbose_name': 'Revisión de Campo',
                'verbose_name_plural': 'Revisiones de Campo',
                'unique_together': {('content_type', 'object_id', 'reviewer', 'field_name')},
            },
        ),
    ]
