# Generated by Django 5.1.7 on 2025-07-29 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_estrategias', '0002_reviewaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewAccess',
        ),
    ]
