# Generated by Django 5.1.7 on 2025-07-09 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadoresFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio_final', models.BooleanField(default=False)),
                ('feedback', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retroalimentación de Indicadores',
                'verbose_name_plural': 'Retroalimentaciones de Indicadores',
            },
        ),
    ]
