# Generated by Django 5.1.7 on 2025-07-09 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewIndicadorProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=255, verbose_name='Nombre del indicador')),
                ('ped_alignment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alineación al PED')),
                ('national_plan_alignment', models.CharField(max_length=255, verbose_name='Alineación al PND')),
                ('ods_alignment', models.JSONField(verbose_name='ODS (array de texto)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('periodicity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Periodicidad')),
                ('trend', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sentido del indicador')),
                ('baseline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Línea base')),
                ('goal2028', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta 2028')),
                ('goal2040', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta 2040')),
                ('sources', models.JSONField(verbose_name='Fuentes (lista de objetos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
