# Generated by Django 5.1.7 on 2025-07-10 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_indicador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newindicadorproposal',
            name='goal2028',
        ),
        migrations.RemoveField(
            model_name='newindicadorproposal',
            name='goal2040',
        ),
        migrations.AddField(
            model_name='newindicadorproposal',
            name='goal_2028',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newindicadorproposal',
            name='goal_2040',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newindicadorproposal',
            name='indicador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='baseline',
            field=models.CharField(blank=True, default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='description',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='indicator_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='national_plan_alignment',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='ods_alignment',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='ped_alignment',
            field=models.CharField(blank=True, default='hola2025', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='periodicity',
            field=models.CharField(blank=True, default='Sin periodicidad', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='sources',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='trend',
            field=models.CharField(blank=True, default='Sin tendencia', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
