# Generated by Django 5.1.7 on 2025-07-10 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_indicador', '0002_remove_newindicadorproposal_goal2028_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='indicador',
            field=models.CharField(blank=True, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\-]+$', 'Solo letras, números, guion y guion bajo')]),
        ),
    ]
