# Generated by Django 5.1.7 on 2025-07-16 17:28

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_indicador', '0003_alter_newindicadorproposal_indicador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newindicadorproposal',
            name='indicador',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[\\w\\-]+$', 'Solo letras, números, guion y guion bajo')]),
        ),
        migrations.AddConstraint(
            model_name='newindicadorproposal',
            constraint=models.UniqueConstraint(fields=('user', 'indicador'), name='unique_indicador_per_user'),
        ),
    ]
