# Generated by Django 5.1.7 on 2025-07-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_indicador', '0004_alter_newindicadorproposal_indicador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newindicadorproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
